// WHAT THE ENGINE SHIPS, read from the engine rather than copied out of it (R-13).
//
// ============================================================================================
// WHY THIS FILE EXISTS. The hub has to tell app content from a creator's own: a calendar named in
// a save is only interesting if Star System Explorer did not ship it, and `/images/star_types/G.webp`
// on a node is app artwork rather than a picture anybody uploaded. Until now both were decided by
// LISTS HARDCODED HERE, copied out of the engine's repo by hand.
//
// That list drifted within an hour of being written the first time, and it had drifted again by
// the time this file replaced it: the tag-category baseline said nine, the engine had grown to
// thirteen, and every map carrying the newer four was reported as having up to four custom
// categories it did not have. A hardcoded copy is a standing promise to notice a change in
// another repository, and the promise is always eventually broken.
//
// `https://<engine>/shipped-content.json` is that promise turned into a fetch. It is GENERATED by
// the engine's own build and its suite fails if a star image is added or a calendar renamed
// without rebuilding it, so it is authoritative for the build it names.
//
// ============================================================================================
// THE RULE WHEN IT IS NOT THERE: SAY NOTHING, NEVER GUESS. A facet with no baseline would count
// every shipped calendar as custom - the exact failure the baselines exist to prevent, and worse
// than showing no facet at all, because a browser who learns the pills lie stops reading all of
// them. So `baselineFor` returns null when the list is unknown and the rule is SKIPPED.
// ============================================================================================

/** The manifest as the engine serves it. Lists are absent, not empty, when a build omits them. */
export interface ShippedManifest {
  appVersion: string;
  bundleFormat?: number;
  /** Every path under one of these is app artwork; anything else on a node came from the creator. */
  appAssetPrefixes?: string[];
  calendars?: string[];
  tagCategories?: string[];
  starterModels?: string[];
  gases?: string[];
  liquids?: string[];
  fuels?: string[];
  appImages?: { starTypes?: string[]; planetTypes?: string[] };
}

/** The lists a facet rule can take its baseline from, by the manifest's own field names. */
export type BaselineKey = 'calendars' | 'tagCategories' | 'starterModels' | 'gases' | 'liquids' | 'fuels';

const BASELINE_KEYS: BaselineKey[] = ['calendars', 'tagCategories', 'starterModels', 'gases', 'liquids', 'fuels'];

export const isBaselineKey = (v: unknown): v is BaselineKey =>
  typeof v === 'string' && (BASELINE_KEYS as string[]).includes(v);

/** Strings only, and only when the field is genuinely a list. An empty list is a real answer. */
function strings(value: unknown): string[] | undefined {
  if (!Array.isArray(value)) return undefined;
  return value.filter((v): v is string => typeof v === 'string' && !!v.trim()).map((v) => v.trim());
}

/**
 * Read a fetched document as a manifest, or refuse it.
 *
 * `appVersion` is the one required field: it is what makes a cached copy attributable to a build,
 * and a document without it is not this document. Everything else is optional, because a manifest
 * that grows a field must not break a hub that has not heard of it, and a manifest that loses one
 * must degrade to "unknown" rather than to "empty" - see the rule at the top of this file.
 */
export function parseShippedManifest(value: unknown): ShippedManifest | null {
  if (!value || typeof value !== 'object' || Array.isArray(value)) return null;
  const doc = value as Record<string, unknown>;
  const appVersion = typeof doc.appVersion === 'string' ? doc.appVersion.trim() : '';
  if (!appVersion) return null;

  const images = doc.appImages && typeof doc.appImages === 'object' ? (doc.appImages as Record<string, unknown>) : null;

  return {
    appVersion,
    bundleFormat: typeof doc.bundleFormat === 'number' ? doc.bundleFormat : undefined,
    appAssetPrefixes: strings(doc.appAssetPrefixes),
    calendars: strings(doc.calendars),
    tagCategories: strings(doc.tagCategories),
    starterModels: strings(doc.starterModels),
    gases: strings(doc.gases),
    liquids: strings(doc.liquids),
    fuels: strings(doc.fuels),
    appImages: images
      ? { starTypes: strings(images.starTypes), planetTypes: strings(images.planetTypes) }
      : undefined
  };
}

/** The shipped names a rule compares against, or null when this build does not say. */
export function baselineFor(manifest: ShippedManifest | null | undefined, key: BaselineKey): string[] | null {
  const list = manifest?.[key];
  return Array.isArray(list) ? list : null;
}

/**
 * Is this node asset one the APP ships, rather than one a creator brought?
 *
 * With a manifest this is exact: `appAssetPrefixes` is the engine's own answer. Without one it
 * falls back to the prefix rule the hub used before R-13 - broader, and it will call a broken
 * site-absolute path app artwork, which is the same thing it has always done. This fallback is
 * safe in a way a guessed NAME list is not: it miscounts an informational number, where a guessed
 * baseline invents a facet.
 */
export function isAppAsset(url: unknown, manifest: ShippedManifest | null | undefined): boolean {
  const path = typeof url === 'string' ? url.trim() : '';
  if (!path || path.startsWith('assets/') || path.startsWith('data:')) return false;
  const prefixes = manifest?.appAssetPrefixes;
  if (prefixes && prefixes.length) return prefixes.some((p) => path.startsWith(p));
  return path.startsWith('/images/') || path.startsWith('/models/');
}
