// THE CLIPS THE ENGINE STREAM TESTS R-19 WITH, generated by the hub's own builder (D-71).
//
// ============================================================================================
// The owner, 2026-09-08, while R-19 was being built on the engine side: *"you have some example
// clipboards to test it with - a desired outcome?"*
//
// So: real clips, written to `docs/clips/`, produced by `buildClip` and `buildRulesClip` themselves
// rather than typed out by hand. A hand-written fixture is a GUESS at what the hub emits, and a
// paste target built against a guess passes its tests and fails on the first real clipboard.
//
// THIS FILE BOTH GENERATES AND CHECKS THEM. Running the suite rewrites the files and asserts the
// shape, so a committed fixture can never drift from what `buildClip` actually produces - if the
// envelope changes, `git status` says the fixtures moved and the assertions say whether that was
// intended.
//
// The nodes are REAL: they come out of `tests/fixtures/creator-hub-bundle.sse.zip`, which is the
// engine's own export. Only the custom rules are added, because no real save on hand has any.
// ============================================================================================
import { describe, it, expect } from 'vitest';
import { readFileSync, writeFileSync, mkdirSync } from 'node:fs';
import { buildClip, buildRulesClip, clipText, type ClipNode } from '../src/lib/bundle/clip';
import { openBundle } from '../src/lib/bundle/open';
import { normalise } from '../src/lib/bundle/normalise';
import { readOverrides, overridesFrom, sameDefinition } from '../src/lib/bundle/overrides';

const OUT = 'docs/clips';

const SOURCE = {
  site: 'StarSystemX Explorers',
  url: 'https://explorers.starsystemx.com/s/contract-reach',
  title: 'Contract Reach',
  creator: 'FrunkQ'
};

/** A liquid, an engine and a fuel - one list kind, one id-keyed kind, and one the engine looks up. */
const RULES = {
  liquids: [
    { name: 'unobtainium', label: 'Liquid Unobtainium', meltK: 20, boilK: 90, colorHex: '#7fd4c1' }
  ],
  engineDefinitions: [
    { id: 'q-drive', name: 'Q Drive', type: 'fusion', fuel_type_id: 'dt-slush', thrust_kN: 900, efficiency_isp: 12000 }
  ],
  fuelDefinitions: [
    { id: 'dt-slush', name: 'D-T Slush', density_kg_per_m3: 225, description: 'Cryogenic deuterium-tritium.' }
  ]
};

/** The same liquid NAME with a different boiling point - the conflict case. */
const RIVAL_RULES = {
  liquids: [
    { name: 'unobtainium', label: 'Unobtainium (mine)', meltK: 18, boilK: 140, colorHex: '#c17fd4' }
  ]
};

/** The engine's own nodes, put through the hub's reader exactly as an upload would be. */
function realNodes(): ClipNode[] {
  const opened = openBundle(new Uint8Array(readFileSync('tests/fixtures/creator-hub-bundle.sse.zip')));
  if (!opened.ok) throw new Error('fixture will not open: ' + opened.message);
  const shaped = normalise(opened.doc);
  return [...shaped.bodies, ...shaped.constructs].map((n) => ({
    node_id: n.node_id, parent_id: n.parent_id, snippet: n.snippet, tags: []
  })) as ClipNode[];
}

/** Point a body at the custom liquid, so the paste has something to resolve. */
function usingTheLiquid(nodes: ClipNode[]): ClipNode[] {
  return nodes.map((n) =>
    n.node_id === 'planet-b'
      ? { ...n, snippet: { ...(n.snippet as object), hydrosphere: { liquid: 'unobtainium', coverage: 0.6 } } }
      : n);
}

function write(name: string, clip: unknown) {
  mkdirSync(OUT, { recursive: true });
  writeFileSync(OUT + '/' + name, clipText(clip as never) + '\n');
}

describe('the R-19 test clips', () => {
  const nodes = usingTheLiquid(realNodes());

  it('1. a body that needs a custom liquid, with the rules that define it', () => {
    // EXPECTED: the planet and its moon paste; the liquid, engine and fuel are added to the
    // destination's own overrides; Bellwether's hydrosphere resolves and its phase is right.
    const clip = buildClip(nodes, 'planet-b', SOURCE, [], RULES)!;
    expect(clip.root).toBe('planet-b');
    expect(clip.nodes.length).toBeGreaterThan(1);
    expect(clip.rulePackOverrides).toEqual(RULES);
    // The thing the paste has to resolve is really in there.
    expect(JSON.stringify(clip.nodes)).toContain('unobtainium');
    write('1-body-with-rules.json', clip);
  });

  it('2. the same clip again - the duplicate case, which is the ordinary one', () => {
    // EXPECTED: nothing added, nothing renamed, no second copy of anything. This is what happens
    // when somebody pastes a star and then one of its planets.
    const clip = buildClip(nodes, 'planet-b', SOURCE, [], RULES)!;
    const again = buildClip(nodes, 'planet-b', SOURCE, [], RULES)!;
    // Byte-identical rules, so "identical" is decidable without any cleverness.
    expect(sameDefinition(clip.rulePackOverrides, again.rulePackOverrides)).toBe(true);
    write('2-same-clip-again.json', again);
  });

  it('3. the same rules with their fields in a different order - the key-order trap', () => {
    // EXPECTED: STILL treated as a duplicate. Nothing added, nothing renamed. A raw text comparison
    // fails this one and renames something that needed no renaming.
    const shuffled = {
      liquids: [
        { colorHex: '#7fd4c1', boilK: 90, meltK: 20, label: 'Liquid Unobtainium', name: 'unobtainium' }
      ],
      fuelDefinitions: RULES.fuelDefinitions,
      engineDefinitions: RULES.engineDefinitions
    };
    expect(sameDefinition(shuffled.liquids[0], RULES.liquids[0])).toBe(true);
    write('3-same-rules-shuffled-keys.json', buildClip(nodes, 'planet-b', SOURCE, [], shuffled)!);
  });

  it('4. a DIFFERENT liquid with the same name - the conflict case', () => {
    // EXPECTED: the destination's own "unobtainium" is NOT touched. The incoming one is renamed and
    // the pasted body is repointed at the new name. This is the one that must not be got wrong:
    // overwriting would silently change bodies the destination already had.
    expect(sameDefinition(RIVAL_RULES.liquids[0], RULES.liquids[0])).toBe(false);
    write('4-conflicting-liquid.json', buildClip(nodes, 'planet-b', SOURCE, [], RIVAL_RULES)!);
  });

  it('5. a rules-only clip - no objects at all', () => {
    // EXPECTED: the liquid is merged; NO body, moon or ship is created; the report says one liquid
    // arrived. `hubClip` refuses a clip that is not a hierarchy today, which is right for a map clip
    // and wrong for this one.
    const one = readOverrides(RULES).filter((i) => i.key === 'unobtainium');
    const clip = buildRulesClip(SOURCE, overridesFrom(one))!;
    expect(clip.nodes).toEqual([]);
    expect(clip.root).toBeUndefined();
    write('5-rules-only.json', clip);
  });

  it('6. a plain clip with no custom rules - the regression check', () => {
    // EXPECTED: exactly today's behaviour. No key, nothing merged, nothing reported. If this one
    // changes, the change has reached clips it had no business reaching.
    const clip = buildClip(realNodes(), 'planet-b', SOURCE)!;
    expect(clip.rulePackOverrides).toBeUndefined();
    write('6-no-rules.json', clip);
  });

  it('7. rules carrying a key this hub has never heard of', () => {
    // EXPECTED: not a refusal. A newer engine key rides along untouched and whatever understands it
    // uses it; the hub stores and relays overrides WHOLE precisely so this works without a release.
    const future = { ...RULES, somethingTheEngineAddedLater: [{ id: 'x', name: 'X' }] };
    const clip = buildClip(nodes, 'planet-b', SOURCE, [], future)!;
    expect(clip.rulePackOverrides).toHaveProperty('somethingTheEngineAddedLater');
    write('7-unknown-future-key.json', clip);
  });
});
