// The shipped-content manifest (R-13): reading it, and refusing anything that is not it.
//
// The manifest is fetched from another site at runtime, which means every shape below is a shape
// this code can actually meet: a 404 page, a half-written document, an older engine with fewer
// fields, a newer one with more.
import { describe, it, expect } from 'vitest';
import { parseShippedManifest, baselineFor, isAppAsset, isBaselineKey } from '../src/lib/bundle/shipped';

/** The real document, abbreviated - beta v3.0.316, fetched 2026-09-06. */
const REAL = {
  _comment: 'GENERATED by scripts/shipped-manifest/build-shipped-manifest.mjs - do not edit by hand.',
  appVersion: '3.0.316',
  bundleFormat: 1,
  appAssetPrefixes: ['/images/planet_types/', '/images/star_types/', '/models/nasa/'],
  calendars: ['Chinese Lunisolar (Simplified)', 'Earth Gregorian', 'Mayan Haab (Simplified)', 'Star Trek Stardate'],
  tagCategories: ['status', 'owner', 'purpose', 'resource', 'class', 'drive', 'frontier',
                  'anomaly', 'universe', 'disposition', 'tech', 'science', 'intrigue'],
  starterModels: ['/models/nasa/cassini.glb', '/models/nasa/iss.glb'],
  appImages: { starTypes: ['/images/star_types/G.webp'], planetTypes: ['/images/planet_types/web20desert20planet.jpg'] },
  gases: ['Ar', 'Astrophage', 'C2H6'],
  liquids: ['ammonia', 'water'],
  fuels: ['fuel-antimatter', 'fuel-xenon']
};

describe('reading the manifest', () => {
  it('reads the real document', () => {
    const m = parseShippedManifest(REAL)!;
    expect(m.appVersion).toBe('3.0.316');
    expect(m.calendars).toHaveLength(4);
    expect(m.tagCategories).toContain('intrigue');
    expect(m.appAssetPrefixes).toContain('/models/nasa/');
    expect(m.appImages?.starTypes).toEqual(['/images/star_types/G.webp']);
  });

  it('refuses anything without an appVersion, which is what makes a copy attributable', () => {
    expect(parseShippedManifest({ calendars: ['Earth Gregorian'] })).toBeNull();
    expect(parseShippedManifest({ appVersion: '  ' })).toBeNull();
  });

  it('refuses what a 404 page or a broken fetch would hand it', () => {
    for (const junk of [null, undefined, '', 'not json', 42, [], ['a'], { html: '<!doctype html>' }]) {
      expect(parseShippedManifest(junk)).toBeNull();
    }
  });

  it('keeps the fields it understands and ignores the rest', () => {
    const m = parseShippedManifest({ appVersion: '9.9.9', calendars: ['One'], somethingNew: [1, 2] })!;
    expect(m.calendars).toEqual(['One']);
    expect((m as any).somethingNew).toBeUndefined();
  });

  it('drops non-strings out of a list rather than refusing the whole manifest', () => {
    const m = parseShippedManifest({ appVersion: '1.0.0', calendars: ['Earth Gregorian', 7, null, ' Spaced '] })!;
    expect(m.calendars).toEqual(['Earth Gregorian', 'Spaced']);
  });
});

describe('a baseline is known, or it is not', () => {
  const m = parseShippedManifest(REAL);

  it('gives the list when the manifest has it', () => {
    expect(baselineFor(m, 'calendars')).toHaveLength(4);
  });

  // The whole point: unknown is not empty. An empty baseline reports every shipped calendar as
  // custom; null tells the rule engine to say nothing at all.
  it('gives null - not an empty list - when it does not', () => {
    expect(baselineFor(null, 'calendars')).toBeNull();
    expect(baselineFor(parseShippedManifest({ appVersion: '1.0.0' }), 'calendars')).toBeNull();
  });

  it('distinguishes a genuinely empty list from a missing one', () => {
    expect(baselineFor(parseShippedManifest({ appVersion: '1.0.0', fuels: [] }), 'fuels')).toEqual([]);
  });

  it('knows which names a config row may use', () => {
    expect(isBaselineKey('tagCategories')).toBe(true);
    expect(isBaselineKey('unicorns')).toBe(false);
    expect(isBaselineKey(null)).toBe(false);
  });
});

describe('app artwork against a creator\'s own', () => {
  const m = parseShippedManifest(REAL);

  it('is the manifest prefixes when there is a manifest', () => {
    expect(isAppAsset('/images/star_types/G.webp', m)).toBe(true);
    expect(isAppAsset('/models/nasa/iss.glb', m)).toBe(true);
    // Site-absolute, but nothing the app ships sits there: not app artwork, whatever it looks like.
    expect(isAppAsset('/images/mine/secret-base.png', m)).toBe(false);
  });

  it('never counts what the bundle carries, which is the hub\'s to moderate', () => {
    expect(isAppAsset('assets/images/moon.jpg', m)).toBe(false);
    expect(isAppAsset('data:image/png;base64,AAAA', m)).toBe(false);
    expect(isAppAsset('https://elsewhere.example/x.png', m)).toBe(false);
  });

  it('falls back to the pre-R-13 prefix rule with no manifest', () => {
    expect(isAppAsset('/images/star_types/G.webp', null)).toBe(true);
    expect(isAppAsset('/images/mine/secret-base.png', null)).toBe(true); // broader, and honest about it
    expect(isAppAsset('assets/images/moon.jpg', null)).toBe(false);
  });

  it('never throws on hostile input', () => {
    for (const v of [null, undefined, 42, {}, []]) expect(isAppAsset(v, m)).toBe(false);
  });
});
