// FETCH what the engine ships, and remember it (R-13, D-36).
//
// ============================================================================================
// The engine serves `shipped-content.json`, generated by its own build and pinned by its own
// suite. `bundle/shipped.ts` says why the hub reads it instead of keeping a copy. This file is
// the part that touches the network, so everything here is about NOT depending on that network.
//
// THE CACHE IS IN R2, not in the config table. A machine-written row sitting among the gates is
// noise the owner has to learn to ignore, and the bundles bucket already holds the hub's other
// derived artefacts (the backups). One small object, overwritten in place.
//
// THE CACHE IS ALSO THE FALLBACK. When the engine is unreachable the last good answer is used,
// however old - a manifest goes stale by a calendar at a time, and a stale baseline is enormously
// better than none (see `bundle/shipped.ts`: none means the facet lies). A FAILED check is
// remembered too, so a beta that is down does not cost every upload a timeout: the next attempt
// waits, exactly as a successful one does, just for less long.
//
// NOTHING HERE THROWS. An upload must not fail because another site was slow.
// ============================================================================================
import { parseShippedManifest, type ShippedManifest } from '$lib/bundle/shipped';
import { isHttpUrl } from '$lib/addresses';
import type { HubEnv } from './db';

/** One object in the bundles bucket, overwritten in place. Never served to anyone. */
const CACHE_KEY = 'cache/shipped-content.json';

/** How long a good answer stands before it is checked again. */
const FRESH_MS = 6 * 60 * 60 * 1000;
/** How long a FAILED check stands, so an engine that is down costs one slow request, not all of them. */
const RETRY_MS = 15 * 60 * 1000;
/** The engine gets this long to answer before the upload goes on without it. */
const TIMEOUT_MS = 4000;

export interface ShippedCache {
  /** The last manifest that parsed. Null only before the first successful fetch. */
  manifest: ShippedManifest | null;
  /** When that manifest was fetched. */
  fetched_at: string | null;
  /** When the engine was last asked, successfully or not. */
  checked_at: string;
  /** Where it was asked. */
  source: string;
  /** Why the last check failed, when it did. */
  error?: string;
}

/** Read the cache without asking the engine anything. For the admin page. */
export async function readCache(env: HubEnv): Promise<ShippedCache | null> {
  try {
    const object = await env.HUB_BUNDLES.get(CACHE_KEY);
    if (!object) return null;
    const parsed = JSON.parse(await object.text()) as ShippedCache;
    return parsed && typeof parsed === 'object' ? { ...parsed, manifest: parseShippedManifest(parsed.manifest) } : null;
  } catch {
    return null;
  }
}

async function writeCache(env: HubEnv, cache: ShippedCache): Promise<void> {
  try {
    await env.HUB_BUNDLES.put(CACHE_KEY, JSON.stringify(cache, null, 2), {
      httpMetadata: { contentType: 'application/json', cacheControl: 'no-store' }
    });
  } catch {
    // A cache that cannot be written is a slower hub, not a broken one.
  }
}

/** Ask the engine, once, with a deadline. Returns the parsed manifest or the reason it did not. */
export async function fetchManifest(url: string): Promise<{ manifest: ShippedManifest } | { error: string }> {
  // `"off"` in the row - or anything else that is not an address - is a deliberate off switch, not
  // a fetch to attempt. Same rule as `openLink`.
  if (!isHttpUrl(url)) return { error: 'no manifest URL is configured' };
  let res: Response;
  try {
    res = await fetch(url, {
      headers: { accept: 'application/json' },
      signal: typeof AbortSignal?.timeout === 'function' ? AbortSignal.timeout(TIMEOUT_MS) : undefined
    });
  } catch (e) {
    return { error: 'could not be reached: ' + ((e as Error)?.message ?? String(e)) };
  }
  if (!res.ok) return { error: 'answered ' + res.status };

  let body: unknown;
  try {
    body = await res.json();
  } catch {
    return { error: 'answered something that is not JSON' };
  }
  const manifest = parseShippedManifest(body);
  return manifest ? { manifest } : { error: 'answered JSON that is not a shipped-content manifest' };
}

/**
 * THE ONE ENTRY POINT for reading code: the manifest to derive facets against, or null when the
 * hub has never once managed to fetch it. Cached, refreshed when stale, and never a reason to fail.
 *
 * `force` is the admin's Refresh button: ask now, whatever the cache says.
 */
export async function shippedManifest(
  env: HubEnv, url: string, opts: { force?: boolean } = {}
): Promise<ShippedManifest | null> {
  const cache = await readCache(env);

  if (!opts.force && cache && cache.source === url) {
    const age = Date.now() - Date.parse(cache.checked_at || '');
    const stands = cache.manifest ? FRESH_MS : RETRY_MS;
    if (Number.isFinite(age) && age >= 0 && age < stands) return cache.manifest;
  }

  const result = await fetchManifest(url);
  const now = new Date().toISOString();

  if ('manifest' in result) {
    await writeCache(env, { manifest: result.manifest, fetched_at: now, checked_at: now, source: url });
    return result.manifest;
  }

  // Keep the last good answer and record why today's check failed.
  await writeCache(env, {
    manifest: cache?.source === url ? (cache?.manifest ?? null) : null,
    fetched_at: cache?.source === url ? (cache?.fetched_at ?? null) : null,
    checked_at: now,
    source: url,
    error: result.error
  });
  return cache?.source === url ? (cache?.manifest ?? null) : null;
}
